// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB4xcTEnJ9RxSdcOldcxey64DIopVXhbA',
    appId: '1:112577515365:web:1f6c4ccd0475a2a3555b8c',
    messagingSenderId: '112577515365',
    projectId: 'benevoles-app',
    authDomain: 'benevoles-app.firebaseapp.com',
    storageBucket: 'benevoles-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb2hiv4ddBkM7PIMxpzXmuCy7u2dvcLWE',
    appId: '1:112577515365:android:1d9cf1659fe89623555b8c',
    messagingSenderId: '112577515365',
    projectId: 'benevoles-app',
    storageBucket: 'benevoles-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqnjvvBHaFQVhQh7Jt75EpxOMZte9opz4',
    appId: '1:112577515365:ios:2c1e7c4f0b94c425555b8c',
    messagingSenderId: '112577515365',
    projectId: 'benevoles-app',
    storageBucket: 'benevoles-app.firebasestorage.app',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqnjvvBHaFQVhQh7Jt75EpxOMZte9opz4',
    appId: '1:112577515365:ios:2c1e7c4f0b94c425555b8c',
    messagingSenderId: '112577515365',
    projectId: 'benevoles-app',
    storageBucket: 'benevoles-app.firebasestorage.app',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB4xcTEnJ9RxSdcOldcxey64DIopVXhbA',
    appId: '1:112577515365:web:e910ac5d972b5d60555b8c',
    messagingSenderId: '112577515365',
    projectId: 'benevoles-app',
    authDomain: 'benevoles-app.firebaseapp.com',
    storageBucket: 'benevoles-app.firebasestorage.app',
  );
}
